version: '3.7'

services:
  api-gateway:
    build:
      context: ./backend/ApiGateway
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/ApiGateway/.env
    depends_on:
      - rabbitmq
      

  books-service:
    build:
      context: ./backend/BookService
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/BookService/.env
    depends_on:
      - rabbitmq
      - postgres-books

  users-service:
    build:
      context: ./backend/UserService
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/UserService/.env
    depends_on:
      - rabbitmq
      - postgres-users
      

  
  postgres-books:
   image: postgres:13-alpine
   environment:
    POSTGRES_USER: book_user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: booksdb
   ports:
    - "5433:5432"

  postgres-users:
   image: postgres:13-alpine
   environment:
    POSTGRES_USER: user_user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: usersdb
   ports:
    - "5434:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Web UI RabbitMQ
      - "5672:5672"   # RabbitMQ Port

 